AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi
Globals:
  Function:
      Runtime: java17
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable


Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: ordersapi.lambda.CreateOrderLambda::createOrder     
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
           TableName: !Ref OrdersTable
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: ordersapi.lambda.ReadOrderLambda::readOrder
      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
           TableName: !Ref OrdersTable
Outputs:
  CreateOrderApi:
    Description: API gateway endpoint for creating the order
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders
  CreateOrderFunction:
    Description: Create Order Lambda function ARN
    Value: !GetAtt CreateOrderFunction.Arn
  CreateOrderFunctionIamRole:
    Description: "Create Order Lambda function IAM Role ARN
    Value: !GetAtt CreateOrderFunctionRole.Arn